apiVersion: v1
kind: Secret
metadata:
  name: hcloud-autoscaler-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  config.yaml: |
    token: {{ .Values.hcloud.token }}
    region: {{ .Values.hcloud.region }}
    image: {{ .Values.hcloud.image }}
    ssh_key: {{ .Values.hcloud.sshKey }}
    network: {{ .Values.hcloud.network }}
    node_pools:
    {{- range .Values.autoscaler.nodeGroups }}
      - name: {{ .name }}
        instance_type: {{ .instanceType }}
        min_nodes: {{ .min }}
        max_nodes: {{ .max }}
        {{- $groupName := .name }}
        {{- with index $.Values.hcloud.nodeGroups $groupName }}
        {{- if .cloudInitBase64 }}
        cloud_init: "{{ .cloudInitBase64 }}"
        {{- end }}
        {{- end }}
    {{- end }}
