{{- if .Values.rancher.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rancher-api-token
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  token: {{ .Values.rancher.token | quote }}
{{- end }}
